# Generated by Django 5.2.6 on 2026-10-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_exchangeprogram_alter_department_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO faculty_exchangeprogram (university, languages, places, deadline, description) VALUES
            ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15', 'Найбільший і один з найстаріших університетів Польщі (засн. 1816), із сильними школами гуманітарних і суспільних наук.'),
            ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01', 'Найстаріший університет Бельгії (засн. 1425) і провідний дослідницький університет Європи.'),
            ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20', 'Найстаріший університет Литви та регіону Балтії, заснований 1579 року.'),
            ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15', 'Найстаріший університет Польщі (засн. 1364, Краків), один із найпрестижніших у Центральній Європі.'),
            ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10', 'Провідний дослідницький університет Естонії, заснований 1632 року.'),
            ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30', 'Другий за величиною університет Чехії (Брно), відомий сильними суспільними та правничими школами.');
            """,
            reverse_sql="DELETE FROM faculty_exchangeprogram;",
        ),
    ]