# Generated by Django 5.2.6 on 2026-10-06 16:23

from django.db import migrations


def split_university(apps, schema_editor):
    ExchangeProgram = apps.get_model("faculty", "ExchangeProgram")
    for program in ExchangeProgram.objects.all():
        text = program.university.strip()
        if "(" in text and ")" in text:
            name = text[:text.index("(")].strip()
            country = text[text.index("(") + 1:text.index(")")].strip()
        elif "," in text:
            name, country = text.rsplit(",", 1)
        elif " - " in text:
            name, country = text.split(" - ", 1)
        else:
            name, country = text, ""
        program.university = name.strip()
        program.country = country.strip()
        program.save()


def merge_university(apps, schema_editor):
    ExchangeProgram = apps.get_model("faculty", "ExchangeProgram")
    for program in ExchangeProgram.objects.all():
        if program.country:
            program.university = f"{program.university}, {program.country}"
        program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_exchangeprogram_country'),
    ]

    operations = [
        migrations.RunPython(split_university, merge_university),
    ]