# Generated by Django 5.2.6 on 2026-10-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_split_university_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='places_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
