# Generated by Django 5.2.6 on 2026-10-06 16:38

import re
from django.db import migrations


def places_to_int(apps, schema_editor):
    ExchangeProgram = apps.get_model("faculty", "ExchangeProgram")
    for program in ExchangeProgram.objects.all():
        match = re.search(r"\d+", program.places or "")
        program.places_count = int(match.group()) if match else None
        program.save()


def places_to_text(apps, schema_editor):
    ExchangeProgram = apps.get_model("faculty", "ExchangeProgram")
    for program in ExchangeProgram.objects.all():
        program.places = str(program.places_count) if program.places_count is not None else ""
        program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_exchangeprogram_places_count'),
    ]

    operations = [
        migrations.RunPython(places_to_int, places_to_text),
    ]