# Generated by Django 5.2.6 on 2026-10-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_places_text_to_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
    ]
