# Generated by Django 5.2.6 on 2026-10-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_places_text_to_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='places',
        ),
    ]
